msqyldb:
  image: tutum/mysql:5.6
  container_name: db
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/containers/data/mysql:/var/lib/mysql
  env_file: ./env/mysqldb.env

mariadb:
  image: tutum/mariadb:10.1
  container_name: db
  ports:
    - "3307:3306"
  volumes:
    - /var/lib/containers/data/mariadb:/var/lib/mysql
  env_file: ./env/mariadb.env

php:
  image: phpcomposer:5.6
  container_name: php
  volumes:
    - /DevOps/conf/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - /var/www/html:/usr/share/nginx/html/
  links:
    - db

web:
  image: nginx
  container_name: web
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/www/html:/usr/share/nginx/html/
    - /DevOps/conf/nginx:/etc/nginx/conf.d/
  links:
    - php