mysqldb:
  image: tutum/mysql:5.6
  container_name: mysqldb
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/containers/data/mysql:/var/lib/mysql
  env_file: ./env/mysqldb.env

mariadb:
  image: mariadb
  container_name: mariadb
  ports:
    - "3307:3306"
  volumes:
    - /var/lib/containers/data/mariadb:/var/lib/mysql
  env_file: ./env/mariadb.env

redis:
  image: redis
  container_name: redis
  ports:
    - "6379:6379"
  volumes:
    - /var/lib/containers/data/redis:/data

php:
  image: phpcomposer:5.6
  container_name: php
  volumes:
    - /DevOps/conf/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - /var/www/html:/var/www/html/
  links:
    - mysqldb
    - redis
    - mariadb

web:
  image: nginx
  container_name: web
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/www/html:/var/www/html/
    - /DevOps/conf/nginx/conf.d:/etc/nginx/conf.d/
    - /DevOps/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - php

# go:
#   image: golang:1.5
#   container_name: go
#   volumes:
#     - /var/www/html:/var/www/html/
#   ports:
#     - "8080:8080"