mysqldb:
  image: tutum/mysql:5.6
  container_name: mysqldb
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/containers/data/mysql:/var/lib/mysql
  env_file: ./env/mysqldb.env

mariadb:
  image: tutum/mariadb:10.1
  container_name: mariadb
  ports:
    - "3307:3306"
  volumes:
    - /var/lib/containers/data/mariadb:/var/lib/mysql
  env_file: ./env/mariadb.env

redis:
  image: redis
  container_name: redis
  ports:
    - "6379:6379"
  volumes:
    - /var/lib/containers/data/redis:/data

php:
  image: phpcomposer:5.6
  container_name: php
  volumes:
    - /DevOps/conf/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - /var/www/html:/usr/share/nginx/html/
  links:
    - mysqldb
    - redis
    - mariadb

web:
  image: nginx
  container_name: web
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/www/html:/usr/share/nginx/html/
    - /DevOps/conf/nginx:/etc/nginx/conf.d/
  links:
    - php